### ISSUE TITLE
uninitialized constant AWS

### ISSUE THREAD

**Issue by athieme** [ThoughtWorksStudios/elasticsearch-opsworks#3]
I'm getting the following. I suppose it's related to having v2 installed and maybe this project requires v1 but I'm not sure how to dig myself out of that hole.

```
10:59 PM elasticsearch-opsworks> rake provision --trace
** Invoke provision (first_time)
** Execute provision
rake aborted!
uninitialized constant AWS
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/ext/module.rb:36:in `const_missing'
/Users/athieme/Source/league/elasticsearch-opsworks/Rakefile:160:in `block in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:228:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:228:in `block in execute'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:223:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:223:in `execute'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:166:in `block in invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:159:in `invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:152:in `invoke'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:143:in `invoke_task'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:101:in `block (2 levels) in top_level'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:101:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:101:in `block in top_level'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:110:in `run_with_threads'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:95:in `top_level'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:73:in `block in run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:70:in `run'
/usr/bin/rake:37:in `<main>'
Tasks: TOP => provision
10:59 PM elasticsearch-opsworks>
```

**Comment by sharmaansh21** [comment]
@athieme you need to install aws-sdk version 1.

**Comment by betarelease** [comment]
Hi Alex 
Yes like Anshul says You need aws sdk v1. We built it in those days and have not upgraded it. If you do upgrade it pl send a pull request. 

Thanks. 
- Sudhindra Rao

**Comment by xli** [comment]
@athieme,
master branch supports v2 now, @optimisticanshul did the work,
you can check it out, and let us know if you found any problem
